vesselapi/integrations

- package.json
- src/sdk/action.ts
- src/sdk/client.ts
- src/sdk/platform.ts
- src/sdk/types.ts
- src/sdk/unification.ts
> chore: cleanup the nativeless type

- package.json
- src/platforms/active-campaign/index.ts
- src/platforms/aircall/index.ts
- src/sdk/auth.ts
- src/sdk/types.ts
> quetion type to text

- package.json
- src/platforms/salesloft/actions/cadences/import.ts
- src/platforms/salesloft/client.ts
- src/platforms/salesloft/schemas.ts
> fix: salesloft client fixes

- package.json
- src/platforms/slack/schemas.ts
> fix: handle additional slack auth resp

- package.json
- src/platforms/hubspot/schemas.ts
> Making timestamp optional for input

- package.json
- src/platforms/hubspot/actions/calls/dispositions.ts
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
> HubSpot disposition action

- package.json
- src/platforms/hubspot/client.ts
> Fixing hs_timestamp

- package.json
- src/platforms/hubspot/index.ts
> Add calls dispositions endpoint

- package.json
- src/platforms/hubspot/schemas.ts
> Making HS properties partial

- package.json
- src/platforms/apollo/actions/accounts/search.ts
- src/platforms/apollo/actions/activities/list.ts
- src/platforms/apollo/actions/custom-fields/list.ts
- src/platforms/apollo/actions/email-accounts/list.ts
- src/platforms/apollo/actions/emails/search.ts
- src/platforms/apollo/actions/labels/search.ts
- src/platforms/apollo/actions/mappers.ts
- src/platforms/apollo/actions/people/search.ts
- src/platforms/apollo/actions/sequences/search.ts
- src/platforms/apollo/actions/users/search.ts
- src/platforms/apollo/client.ts
- src/platforms/apollo/index.ts
- src/platforms/apollo/schemas.ts
> feat: apollo people and label search actions

- package.json
- src/platforms/apollo/actions/accounts/search.ts
- src/platforms/apollo/actions/contacts/search.ts
- src/platforms/apollo/actions/labels/search.ts
- src/platforms/apollo/actions/mappers.ts
- src/platforms/apollo/actions/people/search.ts
- src/platforms/apollo/actions/sequences/search.ts
- src/platforms/apollo/actions/users/search.ts
> fix: return pagination object for apollo actions

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/constants.ts
- src/platforms/hubspot/index.ts
- src/platforms/hubspot/schemas.ts
- src/platforms/index.ts
- src/sdk/client.ts
> HubSpot Client

- package.json
- src/platforms/salesforce/actions/contacts/create.ts
- src/platforms/salesforce/actions/contacts/find.ts
- src/platforms/salesforce/actions/query-builder.ts
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/constants.ts
- src/platforms/salesforce/schemas.ts
> Salesforce Client

- package.json
- src/platforms/salesforce/actions/query-builder.ts
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/schemas.ts
> feat: email optional for contact SF and adding better associations.

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
> feat: adding native support to hubspot

- package.json
- src/platforms/hubspot/schemas.ts
> fixing contact list contact schema

- package.json
- src/platforms/salesforce/actions/query-builder.ts
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/constants.ts
- src/platforms/salesforce/schemas.ts
> feat: adding support for remaining SF objects

- package.json
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/constants.ts
- src/platforms/salesforce/schemas.ts
> feat: [sf] add content notes

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
> fix: [hs] using limit instead of page size

- package.json
- src/platforms/apollo/index.ts
- src/platforms/hubspot/schemas.ts
> chore: fix apollo tutorial link

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
> fix: [hubspot] upsert response schema should only contain id

- package.json
- src/platforms/active-campaign/index.ts
- src/platforms/aircall/client.ts
- src/platforms/apollo/client.ts
- src/platforms/apollo/index.ts
- src/platforms/hubspot/client.ts
- src/platforms/mailchimp/client.ts
- src/platforms/mailchimp/index.ts
- src/platforms/microsoft/client.ts
- src/platforms/outreach/client.ts
- src/platforms/outreach/index.ts
- src/platforms/ringcentral/index.ts
- src/platforms/salesforce/index.ts
- src/platforms/salesloft/client.ts
- src/platforms/slack/client.ts
- src/sdk/client.ts
> fix: client url leading slashes

- package.json
- src/platforms/hubspot/schemas.ts
- src/platforms/salesforce/schemas.ts
Removed all instances of downstream validators that use passthrough
> removing passthrough

- package.json
- src/platforms/apollo/schemas.ts
- src/platforms/dialpad/schemas.ts
- src/platforms/hubspot/schemas.ts
- src/platforms/ringcentral/schemas.ts
- src/platforms/salesforce/schemas.ts
> change z.object.passthrough to z.record

- package.json
- src/platforms/salesforce/schemas.ts
> fix: [sf] event to include event relations

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
- src/platforms/salesforce/actions/query-builder.ts
- src/platforms/salesforce/client.ts
> feat: [sf,hs] batch gets

- package.json
- src/platforms/salesforce/schemas.ts
> Add `ContactId` to Salesforce Deal Create

- package.json
- src/platforms/salesforce/actions/query-builder.ts
- src/platforms/salesforce/client.ts
> feat: [sf] search

- package.json
- src/platforms/hubspot/index.ts
> fix: [hs] adding retry logic to invalid auth for v4 errors

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
> feat: [hs] search

- package.json
- src/platforms/hubspot/actions/mappers.ts
- src/platforms/hubspot/schemas.ts
> feat: add hs_all_contact_vids to hubspot contact

- package.json
- src/platforms/apollo/client.ts
> fix: Type->Types for apollo email filter

- package.json
- src/platforms/hubspot/schemas.ts
> fix: add missing ids to hubspot deal and account objects

- package.json
- src/platforms/hubspot/index.ts
- src/platforms/salesforce/index.ts
> fix: export hubspot actions

- package.json
- src/platforms/hubspot/schemas.ts
> fix: add missing `hs_task_type` to tasks

- src/platforms/salesforce/schemas.ts
> fix: removing sf type from tasks

- package.json
- src/platforms/apollo/client.ts
- src/platforms/outreach/actions/prospects/list.ts
- src/platforms/outreach/client.ts
- src/platforms/salesloft/actions/people/list.ts
- src/platforms/salesloft/client.ts
> feat: add tag and sequence filtering properties to the SEP integrations

- package.json
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/schemas.ts
- src/sdk/client.ts
> fix: using cursor for listsviews

- src/platforms/salesloft/index.ts
> Set oauth2 to be default for salesloft

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
> feat: allowing hubspot to take in properties

- package.json
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/constants.ts
- src/platforms/salesforce/index.ts
- src/platforms/salesforce/schemas.ts
- src/sdk/client.ts
> feat: adding raw request to client

- package.json
- src/platforms/salesforce/actions/query-builder.ts
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/constants.ts
- src/platforms/salesforce/schemas.ts
> fix: fixing sf client for bulk queries

- package.json
- src/platforms/salesforce/schemas.ts
> fix: sf validators

- package.json
- src/sdk/validators.ts
> fix: better datetime validator

- package.json
- src/platforms/salesforce/schemas.ts
> fix: sf client validators

- package.json
- src/platforms/salesforce/schemas.ts
> fix: sf account validator

- package.json
- src/platforms/apollo/client.ts
> feat: Add label and sequence filtering to contact search

- package.json
- src/platforms/apollo/client.ts
> feat: allow for apollo contact sorting

- package.json
- src/sdk/client.ts
- src/sdk/error.ts
- src/sdk/types.ts
- yarn.lock
> use undici.request to make get + json requests

- package.json
- src/platforms/salesforce/actions/list-view-results/find.ts
- src/platforms/salesforce/actions/list-views/find.ts
- src/platforms/salesforce/actions/list-views/list.ts
- src/platforms/salesforce/actions/query-builder.ts
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/schemas.ts
> fix: salesforce batch pagination

- package.json
- src/platforms/hubspot/index.ts
- src/platforms/pipedrive/index.ts
- src/platforms/slack/index.ts
- src/sdk/auth.ts
- src/sdk/client.ts
- src/sdk/types.ts
> chore: Changing isRetryable implementation

- package.json
- src/sdk/types.ts
> chore: Remove dispatcher from typing

- package.json
- src/platforms/hubspot/index.ts
- src/platforms/pipedrive/index.ts
- src/platforms/slack/index.ts
- src/sdk/auth.ts
- src/sdk/client.ts
- src/sdk/error.ts
- src/sdk/types.ts
- yarn.lock
> feat: Rollback undici

- package.json
- pnpm-lock.yaml
- src/platforms/apollo/actions/calls/create.ts
- src/platforms/apollo/actions/calls/dispositions-list.ts
- src/platforms/apollo/actions/calls/dispositions.ts
- src/platforms/apollo/actions/mappers.ts
- src/platforms/apollo/actions/tasks/mark-complete.ts
- src/platforms/apollo/actions/tasks/search.ts
- src/platforms/apollo/client.ts
- src/platforms/apollo/index.ts
- src/platforms/apollo/schemas.ts
> feat: adding apollo actions

- package.json
- src/platforms/apollo/actions/calls/dispositions-list.ts
- src/platforms/apollo/schemas.ts
> fix: apollo dispositions can be undefined

- package.json
- src/platforms/salesforce/actions/query-builder.ts
- src/platforms/salesforce/client.ts
> fix: adding cursor to salesforce batchRead

- package.json
- src/platforms/apollo/actions/calls/dispositions-list.ts
- src/platforms/apollo/actions/tasks/search.ts
- src/platforms/apollo/client.ts
- src/platforms/apollo/schemas.ts
> fix: apollo tasks and calls

- package.json
- src/platforms/apollo/client.ts
> fix: updating task search

- package.json
- src/platforms/apollo/actions/accounts/search.ts
- src/platforms/apollo/actions/contacts/search.ts
- src/platforms/apollo/actions/labels/search.ts
- src/platforms/apollo/actions/mappers.ts
- src/platforms/apollo/actions/people/search.ts
- src/platforms/apollo/actions/sequences/search.ts
- src/platforms/apollo/actions/tasks/search.ts
- src/platforms/apollo/actions/users/search.ts
> fix: apollo page number

- package.json
- src/platforms/apollo/actions/mappers.ts
> fix: include contact and account object onto tasks

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
- src/platforms/pipedrive/client.ts
- src/platforms/pipedrive/schemas.ts
- src/sdk/client.ts
> feat: Add conn info api to HubSpot and Pipedrive

- package.json
- src/platforms/apollo/actions/tasks/search.ts
- src/platforms/apollo/client.ts
- src/platforms/apollo/constants.ts
> feat: updating per_page size for search tasks

- package.json
- src/platforms/apollo/actions/calls/create.ts
- src/platforms/apollo/actions/calls/details.ts
- src/platforms/apollo/actions/mappers.ts
- src/platforms/apollo/index.ts
- src/platforms/apollo/schemas.ts
> feat: adding apollo fields and endpoints

- package.json
- src/platforms/apollo/actions/calls/create.ts
- src/platforms/apollo/schemas.ts
> fix: include userid in apollo call create

- package.json
- src/platforms/hubspot/index.ts
- src/sdk/client.ts
> fix: Fix hubspot auth retry logic

- src/platforms/hubspot/schemas.ts
> fix: fixing hubspot client types

- package.json
- src/platforms/hubspot/schemas.ts
> fix: hubspot options.description is nullish

- package.json
- src/sdk/client.ts
- src/sdk/error.ts
- yarn.lock
> feat: add strict option to clients

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
> fix: hs_email_bounce_error_detail_status_code can be string

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
> fix: expose sort property in hubspot

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
> feat: add associations batch reads for hubspot

- package.json
- src/platforms/apollo/client.ts
> fix: apollo pagination bug

- package.json
- src/platforms/outreach/actions/tags/list.ts
- src/platforms/outreach/client.ts
- src/platforms/outreach/constants.ts
- src/platforms/outreach/index.ts
> feat: outreach tags

- package.json
- src/platforms/apollo/client.ts
- src/sdk/client.ts
- src/sdk/query-string.ts
- src/sdk/tests/query-string.test.ts
> support query string array

- package.json
- src/sdk/client.ts
> fix: query string array

- package.json
- src/sdk/client.ts
> fix: non-json body properly parsed

- package.json
- src/platforms/apollo/actions/tasks/search.ts
- src/platforms/apollo/client.ts
> feat: Add emailer_campaign_id to apollo tasks search

- package.json
- src/platforms/apollo/actions/tasks/search.ts
- src/platforms/apollo/client.ts
> feat: Missing params in apollo task search

- package.json
- src/platforms/pipedrive/client.ts
- src/platforms/pipedrive/schemas.ts
- src/sdk/validators.ts
> fix: pipedrive fixes

- package.json
- src/platforms/monday/actions/graphql/query.ts
> fix: fixing monday.com .data

- package.json
- src/platforms/monday/actions/boards/list.ts
- src/platforms/monday/actions/items/create.ts
- src/platforms/monday/client.ts
- src/platforms/monday/constants.ts
- src/platforms/monday/index.ts
- src/platforms/monday/query-builder.ts
- src/platforms/monday/schemas.ts
> feat: adding actions for monday

- package.json
- src/platforms/monday/schemas.ts
> fix: monday fields

- package.json
- src/platforms/salesforce/actions/mappers.ts
- src/platforms/salesforce/actions/query-builder.ts
- src/platforms/salesforce/actions/soql/query.ts
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/index.ts
- src/platforms/salesforce/schemas.ts
> feat: [sf] add soql action

- package.json
- src/platforms/monday/client.ts
- src/platforms/monday/index.ts
- src/sdk/auth.ts
> fix: Monday installs

- package.json
- src/platforms/monday/actions/items/create.ts
- src/platforms/monday/schemas.ts
> returning groups in boards query

- src/platforms/monday/schemas.ts
> fix: updating zod validator for monday

- package.json
- src/platforms/monday/index.ts
- src/sdk/auth.ts
> fix: using install link for monday

- package.json
- src/platforms/monday/actions/boards/list.ts
- src/platforms/monday/actions/groups/create.ts
- src/platforms/monday/actions/items/create.ts
- src/platforms/monday/client.ts
- src/platforms/monday/constants.ts
- src/platforms/monday/index.ts
- src/platforms/monday/query-builder.ts
- src/platforms/monday/schemas.ts
> feat: adding groups/create

- package.json
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/schemas.ts
> feat: allowing queryAll operation for sf job

- package.json
- src/platforms/salesforce/schemas.ts
> fix: sf adding isArchived to event relations

- src/platforms/hubspot/schemas.ts
> fix: hubspot downstream validators for ids

- package.json
- src/platforms/salesforce/schemas.ts
> fix: updating attendee sf schema

- package.json
- src/platforms/salesforce/actions/query-builder.ts
- src/platforms/salesforce/client.ts
> feat: adding calls to client

- package.json
- src/platforms/outreach/schemas.ts
- src/sdk/validators.ts
> fix: add $native to outreach objects

- package.json
- src/platforms/zendesk/client.ts
- src/platforms/zendesk/index.ts
- src/sdk/types.ts
> fix: Zendesk basic support

- package.json
- src/platforms/outreach/client.ts
> fix: outreach sequence step create types

- package.json
- src/sdk/types.ts
> chore: add types to authtypes

- package.json
- src/platforms/outreach/actions/prospects/create.ts
- src/platforms/outreach/actions/prospects/update.ts
> fix: outreach custom field validation

- package.json
- src/platforms/outreach/actions/prospects/create.ts
- src/platforms/outreach/actions/prospects/update.ts
> fix: outreach custom field validation error throws

- package.json
- src/platforms/hubspot/actions/mappers.ts
- src/platforms/hubspot/schemas.ts
> fix: hubspot hs_attachment_ids is string

- package.json
- src/sdk/types.ts
> chore: updating Action return type

- package.json
- src/platforms/dialpad/client.ts
> fix: updating api call for dialpad lists

- package.json
- src/platforms/hubspot/client.ts
- src/platforms/hubspot/schemas.ts
> fix: hubpost association batch reads

- package.json
- src/platforms/pipedrive/client.ts
- src/platforms/pipedrive/schemas.ts
> feat: adding organization to pipedrive

- package.json
- src/platforms/pipedrive/schemas.ts
> fix: updating pipedrive schemas

- package.json
- src/platforms/hubspot/schemas.ts
> fix: hubspot deal closedate empty string transform to null

- package.json
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/schemas.ts
> feat: add custom fields to salesforce

- package.json
- src/platforms/index.ts
> fix: export stripe in platforms index

- package.json
- src/platforms/aircall/client.ts
- src/platforms/aircall/schemas.ts
> feat: add webhook client requests and types to aircall integration

- package.json
- src/platforms/salesforce/client.ts
- src/platforms/salesforce/index.ts
- src/platforms/salesforce/permissions.ts
- src/platforms/salesforce/schemas.ts
- src/sdk/platform.ts
- src/sdk/types.ts
> feat: adding permissions checks for SF

- package.json
- src/platforms/salesforce/client.ts
- src/sdk/client.ts
- src/sdk/error.ts
> feat: handle known client errors for salesforce

- package.json
- src/platforms/salesforce/permissions.ts
- src/platforms/salesforce/schemas.ts
> fix: permissions check for sf

- package.json
- src/platforms/outreach/schemas.ts
- src/platforms/salesforce/permissions.ts
> feat: add title to outreach propsects

- package.json
- src/platforms/outreach/client.ts
> feat: add pageSize to outreach prospects

- package.json
- src/platforms/apollo/client.ts
> feat: ignore 502 gateway errors from apollo
